# Generated by Django 3.2.15 on 2023-09-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('login', models.CharField(max_length=200, verbose_name='Login')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='component',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='foodplan_app.dish', verbose_name='dish'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('term', models.IntegerField(verbose_name='Term')),
                ('breakfast', models.BooleanField(default=True, verbose_name='Breakfast')),
                ('lunch', models.BooleanField(default=True, verbose_name='Lunch')),
                ('dinner', models.BooleanField(default=True, verbose_name='Dinner')),
                ('desserts', models.BooleanField(default=True, verbose_name='Desserts')),
                ('persons_number', models.IntegerField(default=1, verbose_name='Numer of persons')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Cost')),
                ('allergy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='foodplan_app.allergy', verbose_name='Allergy')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='foodplan_app.client')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='foodplan_app.menu')),
            ],
        ),
    ]
