# Generated by Django 4.2.4 on 2023-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0002_auto_20230928_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='example@mail.ru', help_text='example@mail.ru', max_length=200, verbose_name='Mail'),
            preserve_default=False,
        ),
    ]
