# Generated by Django 4.2.4 on 2023-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0003_client_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/test_avatar.png', upload_to=''),
        ),
    ]
