# Generated by Django 4.2.4 on 2023-09-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0005_alter_client_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodplan_app.allergy', verbose_name='Аллергия')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplan_app.subscription', verbose_name='Подписка')),
            ],
        ),
    ]
