# Generated by Django 4.2.4 on 2023-09-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0006_subscriptionallergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='allergy',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subscriptionallergy',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription_allergies', to='foodplan_app.allergy', verbose_name='Аллергия'),
        ),
        migrations.AlterField(
            model_name='subscriptionallergy',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_allergies', to='foodplan_app.subscription', verbose_name='Подписка'),
        ),
    ]
