# Generated by Django 4.2.4 on 2023-09-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0008_tag_dishtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAllergyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='allergy_tags', to='foodplan_app.dish', verbose_name='Dish')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='allergy_tags', to='foodplan_app.allergy', verbose_name='Allergy tag')),
            ],
        ),
    ]
