# Generated by Django 4.2.4 on 2023-09-30 05:36

from django.db import migrations
from django.apps import apps


def load_tags(apps, schema_editor):
     Tag = apps.get_model('foodplan_app', 'Tag')
     Tag.objects.get_or_create(title='Завтрак')
     Tag.objects.get_or_create(title='Обед')
     Tag.objects.get_or_create(title='Ужин')
     Tag.objects.get_or_create(title='Десерт')



class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0009_dishallergytag'),
    ]

    operations = [
        migrations.RunPython(load_tags)
    ]
