# Generated by Django 3.2.15 on 2023-10-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0013_auto_20231001_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='menu',
        ),
    ]
